name: "Azure Login"
description: "Log in to Azure using provided credentials"
inputs:
  azure_credentials:
    description: "Azure credentials JSON"
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}
