name: Build and Push Docker Image to ACR

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      ACR_LOGIN_SERVER: 
        required: true
        type: string

jobs:
  azure-login:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/jobs/az-login.yml@main
    with:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: azure-login 

    steps:
      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ inputs.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build . -t ${{ inputs.ACR_LOGIN_SERVER }}/${{ inputs.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Docker image to ACR
        run: |
          docker push ${{ inputs.ACR_LOGIN_SERVER }}/${{ inputs.IMAGE_NAME }}:${{ github.sha }}

      - name: List Docker images in ACR
        run: |
          az acr repository show-tags --name ${{ inputs.ACR_NAME }} --repository ${{ inputs.IMAGE_NAME }}
