name: SSH to VM, Install Docker, and Deploy Container

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      ACR_LOGIN_SERVER:
        required: true
        type: string
      GITHUB_SHA:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
        default: "22.04"

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p /home/runner/.ssh/
          echo "${{ secrets.VM_SSH_KEY }}" > /home/runner/.ssh/vm_ssh_key
          cat /home/runner/.ssh/vm_ssh_key
          chmod 600 /home/runner/.ssh/vm_ssh_key
          echo "SSH Key has been written to /home/runner/.ssh/vm_ssh_key with permissions:"
          ls -l /home/runner/.ssh/vm_ssh_key
          ssh-keyscan -H 40.85.121.87 >> /home/runner/.ssh/known_hosts
          chmod 644 /home/runner/.ssh/known_hosts
          echo "Known hosts file content:"
          cat /home/runner/.ssh/known_hosts

      - name: Verify SSH Key
        run: |
          ssh-keygen -y -f /home/runner/.ssh/vm_ssh_key
          echo "Attempting SSH to 40.85.121.87"
          ssh -t -i /home/runner/.ssh/vm_ssh_key tung@40.85.121.87 << EOF
            echo "SSH Connection Successful"
          EOF
