name: SSH to VM, Install Docker, and Deploy Container

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      ACR_LOGIN_SERVER:
        required: true
        type: string
      GITHUB_SHA:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
        default: "22.04"

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Execute deployment script on Azure VM
        env:
          ACR_NAME: publicacrdmsnortheurope
          ACR_LOGIN_SERVER: publicacrdmsnortheurope.azurecr.io
          IMAGE_NAME: gettodo
          IMAGE_TAG: latest
          CONTAINER_NAME: my_container
        run: |
          az vm run-command invoke --resource-group rg-dms-northeurope-001 --vm-name vm-be-get-dms-northeurope --command-id RunShellScript --scripts "bash -s" < scripts/deploy_acr_image.sh
