name: SSH to VM, Install Docker, and Deploy Container

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      ACR_LOGIN_SERVER:
        required: true
        type: string

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Run Deployment Commands on VM
        run: |
          az vm run-command invoke \
            --resource-group rg-dms-northeurope-001 \
            --name vm-be-get-dms-northeurope \
            --command-id RunShellScript \
            --scripts '
              # Enable debug mode to print each command as it runs
              set -x

              # Update packages and install Docker if not installed
              if ! command -v docker &> /dev/null; then
                echo "Docker not found, installing..."
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                sudo apt-get update
                sudo apt install -y docker-ce
                sudo systemctl start docker
                sudo systemctl enable docker
              else
                echo "Docker is already installed."
              fi

              # Install Azure CLI if not already installed
              if ! command -v az &> /dev/null; then
                echo "Azure CLI not found, installing..."
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              else
                echo "Azure CLI is already installed."
              fi

              # Login to Azure and ACR
              sudo chmod -R 700 ~/.azure
              sudo chown -R $USER ~/.azure
              az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID
              sudo az acr login --name $ACR_NAME

              # Pull the Docker image from ACR
              sudo docker pull $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

              # Stop and remove any existing container
              sudo docker stop my_container || true
              sudo docker rm my_container || true

              # Run the new container
              sudo docker run -d --name my_container -p 80:80 $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

              # Check if the container is running
              if [ -z "$(docker ps -a -q --filter name=my_container)" ]; then
                echo "Error: No containers are running."
                exit 1
              else
                echo "Container my_container is running successfully."
                docker ps -a
              fi
            ' 
        env:
          ACR_NAME: ${{ inputs.ACR_NAME }}
          ACR_LOGIN_SERVER: ${{ inputs.ACR_LOGIN_SERVER }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          IMAGE_TAG: latest
          CONTAINER_NAME: my_container
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
