name: SSH to VM, Install Docker, and Deploy Container

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      ACR_LOGIN_SERVER:
        required: true
        type: string
      GITHUB_SHA:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
        default: "22.04"

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 40.85.121.87 >> ~/.ssh/known_hosts

      - name: Verify SSH Key
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no tung@40.85.121.87 << 'EOF'
            echo "SSH Connection Successful"
          EOF
